apiVersion: v1
kind: Namespace
metadata:
   name: hrns
---
apiVersion: v1
kind: Pod
metadata:
  name: hrpod
  namespace: hrns
  labels:
     app: myhrpod
     function: HR
spec:
  containers:
    - name: mynginxcontainer
      image: nginx
      ports:
        - containerPort: 80