apiVersion: v1
kind: Namespace
metadata:
   name: developerns
---
apiVersion: v1
kind: ResourceQuota
metadata:
   name: developer-quota
   namespace: developerns
spec:
  hard:
    pods: "2"


---
apiVersion: v1
kind: Pod
metadata:
  name: hrpod
  namespace: developerns
  labels:
     app: myhrpod
     function: HR
spec:
  containers:
    - name: mynginxcontainer
      image: nginx
      ports:
        - containerPort: 80