apiVersion: v1
kind: ReplicationController
metadata:
   name: myfirstpod-rc
   labels:
     app: myfirstapp
spec:
  template: # add the POD defination over here
    metadata:
        name: myfirstpod
        labels:
          app: myfirstapp
    spec:
      containers:
        - name: mynginxcontainer
          image: nginx
          ports:
            - containerPort: 80
  replicas: 2